config/routes.rb
Rails.application.routes.draw do
  # get 'tasks_controller/index'

  # get 'tasks_controller/show'

  # get 'tasks_controller/new'

  # get 'tasks_controller/create'

  # get 'tasks_controller/edit'

  # get 'tasks_controller/update'

  # get 'tasks_controller/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to "/tasks"

  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to "/tasks"
  end

  def destroy
    @task.destroy
    redirect_to "/tasks"

  end

  private
    def task_params
    params.require(:task).permit(:name, :details)
  end
  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>TasksController#create</h1>
<p>Find me in app/views/tasks_controller/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>TasksController#destroy</h1>
<p>Find me in app/views/tasks_controller/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h2>To do list</h2>
<ul>
  <% @tasks.each do |t| %>
  <li><%= t.name %>
    <br>
    <%= link_to "More details", task_path(t)  %>
    <br>
    <%= link_to "Edit", edit_task_path(t)  %>
    <br>
    <%= link_to "Delete", task_path(t), method: :delete  %>
  </br>
  </li>
  <% end %>
</ul>


<%= link_to "Add a new task", new_task_path  %>

app/views/tasks/new.html.erb
<h2>New Task</h2>
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<h3><%= @task.details %></h3>
<%= link_to "Return", tasks_path  %>

app/views/tasks/update.html.erb
<h1>TasksController#update</h1>
<p>Find me in app/views/tasks_controller/update.html.erb</p>